import { ButtonTheme } from '../../Theme/types'

export const buttonThemeLight: ButtonTheme = {
  height: '36px',
  width: 'auto',
  textTransform: 'uppercase',
  fontFamily: 'system, sans-serif',
  fontSize: '14px',
  kerning: '2.5px',
  fontStyle: 'normal',
  fontWeight: '800',
  padding: '0px 22px',
  border: 'none',
  outline: 'none',
  cursor: 'pointer',
  boxShadow: [
    {
      xOffset: '0',
      yOffset: '0',
      blurRadius: '0',
      spreadRadius: '0',
      color: '#CEE5F200',
      inset: false,
    },
  ],
  transform: 'scale(1)',
  transition: [
    {
      transitionProperty: 'box-shadow',
      transitionDuration: '0.3s',
    },
    {
      transitionProperty: 'transform',
      transitionDuration: '0.3s',
    },
    {
      transitionProperty: 'background-color',
      transitionDuration: '0.3s',
    },
  ],
  hovered: {
    height: '40px',
    width: 'auto',
    textTransform: 'uppercase',
    fontFamily: 'system, sans-serif',
    fontSize: '16px',
    kerning: '3px',
    fontStyle: 'normal',
    fontWeight: '800',
    padding: '0px 24px',
    border: 'none',
    outline: 'none',
    cursor: 'pointer',
    transform: 'scale(1.02)',
    boxShadow: [
      {
        xOffset: '1px',
        yOffset: '3px',
        blurRadius: '8px',
        spreadRadius: '0px',
        color: '#CEE5F2',
      },
    ],
    transition: [
      {
        transitionProperty: 'box-shadow',
        transitionDuration: '0.3s',
      },
      {
        transitionProperty: 'transform',
        transitionDuration: '0.3s',
      },
      {
        transitionProperty: 'background-color',
        transitionDuration: '0.3s',
      },
    ],
  },
  clicked: {
    height: '40px',
    width: 'auto',
    textTransform: 'uppercase',
    fontFamily: 'system, sans-serif',
    fontSize: '16px',
    kerning: '3px',
    fontStyle: 'normal',
    fontWeight: '800',
    padding: '0px 24px',
    border: 'none',
    outline: 'none',
    cursor: 'pointer',
    boxShadow: [
      {
        xOffset: '0',
        yOffset: '0',
        blurRadius: '0',
        spreadRadius: '0',
        color: '#CEE5F200',
        inset: false,
      },
    ],
    transition: [
      {
        transitionProperty: 'box-shadow',
        transitionDuration: '0.05s',
      },
      {
        transitionProperty: 'transform',
        transitionDuration: '0.05s',
      },
      {
        transitionProperty: 'background-color',
        transitionDuration: '0.05s',
      },
    ],
  },
  disabled: {
    cursor: 'not-allowed',
    height: '40px',
    width: 'auto',
    textTransform: 'uppercase',
    fontFamily: 'system, sans-serif',
    fontSize: '16px',
    kerning: '3px',
    fontStyle: 'normal',
    fontWeight: '800',
    padding: '0px 24px',
    border: 'none',
    outline: 'none',
  },
}

export const buttonThemeDark: ButtonTheme = {
  height: '36px',
  width: 'auto',
  textTransform: 'uppercase',
  fontFamily: 'system, sans-serif',
  fontSize: '14px',
  kerning: '2.5px',
  fontStyle: 'normal',
  fontWeight: '800',
  padding: '0px 22px',
  border: 'none',
  outline: 'none',
  cursor: 'pointer',
  boxShadow: [
    {
      xOffset: '0',
      yOffset: '0',
      blurRadius: '0',
      spreadRadius: '0',
      color: '#CEE5F200',
      inset: false,
    },
  ],
  transform: 'scale(1)',
  transition: [
    {
      transitionProperty: 'box-shadow',
      transitionDuration: '0.3s',
    },
    {
      transitionProperty: 'transform',
      transitionDuration: '0.3s',
    },
    {
      transitionProperty: 'background-color',
      transitionDuration: '0.3s',
    },
  ],
  hovered: {
    height: '40px',
    width: 'auto',
    textTransform: 'uppercase',
    fontFamily: 'system, sans-serif',
    fontSize: '16px',
    kerning: '3px',
    fontStyle: 'normal',
    fontWeight: '800',
    padding: '0px 24px',
    border: 'none',
    outline: 'none',
    cursor: 'pointer',
    transform: 'scale(1.02)',
    boxShadow: [
      {
        xOffset: '0px',
        yOffset: '3px',
        blurRadius: '3px',
        spreadRadius: '0px',
        color: '#13111d',
      },
    ],
    transition: [
      {
        transitionProperty: 'box-shadow',
        transitionDuration: '0.3s',
      },
      {
        transitionProperty: 'transform',
        transitionDuration: '0.3s',
      },
      {
        transitionProperty: 'background-color',
        transitionDuration: '0.3s',
      },
    ],
  },
  clicked: {
    height: '40px',
    width: 'auto',
    textTransform: 'uppercase',
    fontFamily: 'system, sans-serif',
    fontSize: '16px',
    kerning: '3px',
    fontStyle: 'normal',
    fontWeight: '800',
    padding: '0px 24px',
    border: 'none',
    outline: 'none',
    cursor: 'pointer',
    boxShadow: [
      {
        xOffset: '0',
        yOffset: '0',
        blurRadius: '0',
        spreadRadius: '0',
        color: '#CEE5F200',
        inset: false,
      },
    ],
    transition: [
      {
        transitionProperty: 'box-shadow',
        transitionDuration: '0.05s',
      },
      {
        transitionProperty: 'transform',
        transitionDuration: '0.05s',
      },
      {
        transitionProperty: 'background-color',
        transitionDuration: '0.05s',
      },
    ],
  },
  disabled: {
    cursor: 'not-allowed',
    height: '40px',
    width: 'auto',
    textTransform: 'uppercase',
    fontFamily: 'system, sans-serif',
    fontSize: '16px',
    kerning: '3px',
    fontStyle: 'normal',
    fontWeight: '800',
    padding: '0px 24px',
    border: 'none',
    outline: 'none',
  },
}
